### ISSUE TITLE
Help building on aarch64 needed

### ISSUE THREAD

**Issue by 573** [oxalica/nil#10]
>  [1/161/167 built, 690 copied (4713.5 MiB), 1230.8 MiB DL] building nil-unstable-2022-09-20 (buildPhase)
  nil-unstable> error[E0658]: use of unstable library feature 'bool_to_option'

https://github.com/573/nix-config-1/actions/runs/3092788177/jobs/5004453763#step:5:11319

**Comment by oxalica** [comment]
Your rust version is too old. Please use the latest version of stable rust (currently 1.63.0). I'm sure that rust toolchain have tier-1 aarch64-linux support.

**Comment by 573** [comment]
I'm still learning, thanks so much, this tip will [solve](../../../573/nix-config-1/actions/runs/3098983141/jobs/5017564325#step:5:9544) many questions at once 4 me !
