### ISSUE TITLE
Optionally enable incomplete syntax errors

### ISSUE THREAD

**Issue by IvarWithoutBones** [oxalica/nil#11]
Thanks for all your work on this project, I'm loving it so far! I just have one question/suggestion;

The readme currently states that `Incomplete syntax errors are currently suppressed to avoid noisy outputs during typing`. I would really like to enable reporting these incomplete errors, I don't mind the noisy output and prefer a non-descriptive error rather than none. Would it be feasable to make that a configurable option?

**Comment by oxalica** [comment]
> I would really like to enable reporting these incomplete errors,

That will be eventually enabled. I'm refining parser errors recently.

> Would it be feasable to make that a configurable option?

I opened #13 to track this.

**Comment by IvarWithoutBones** [comment]
Thanks for the quick response, I'll subscribe to that issue :+1:
