### ISSUE TITLE
"I" being capitalised in the README

### ISSUE THREAD

**Issue by GetPsyched** [oxalica/nil#115]
> nil: NIx Language server

I'm fairly certain that this being an error would've caught the eye of someone; raising this issue for that tinge of doubt.

Apologies if the capitalisation was intentional.

**Comment by oxalica** [comment]
:facepalm:  It was intentional, for the acronym. But there has been so many one complaining about that. Maybe I should change it whatever.

**Comment by GetPsyched** [comment]
LOL. I did not know that was an acronym haha.
