### ISSUE TITLE
Do you use HM type inference?

### ISSUE THREAD

**Issue by Septias** [oxalica/nil#116]
Hi @oxalica, I may write some type inference algorithm in my bachelor thesis and I would like to know if you already use a [Hindley-Milner type system](https://en.wikipedia.org/wiki/Hindley-Milner_type_system) in your code or if that might be a newish thing I can try.

Kind regards, Septias :)

**Comment by oxalica** [comment]
> if you already use a [Hindley-Milner type system](https://en.wikipedia.org/wiki/Hindley-Milner_type_system) in your code or if that might be a newish thing I can try.

It is, kinda, but with some casual tweaks on set types. It's designed to focus on keeping more information than get everything correct. So it's not a good reference to type inference in a serious programming language.

> I may write some type inference algorithm in my bachelor thesis.

I'm sorry but it may be better to check other strict typed compilers, or relevant papers for reference instead.
