### ISSUE TITLE
Formatting support

### ISSUE THREAD

**Issue by IvarWithoutBones** [oxalica/nil#12]
I was wondering if it would be possible to integrate a formatter into this project, `rnix-lsp` for example has `nixpkgs-fmt` support which greatly enhances my workflow. In my opinion the best case scenario would be making the path to said formatter configurable, so people can make the decision of which formatter to use themselves.

**Comment by oxalica** [comment]
I'm happy to implement this but... The main issue is that there's currently no acknowledged formatting standard for Nix.
You can see the long long debate under https://github.com/NixOS/rfcs/pull/101

IMO, `nixpkgs-fmt` is too relaxed and does almost nothing, `nixfmt` is too strict and breaks semantics, `alejandra` is ugly and doesn't match existing code style in `nixpkgs`.

**Comment by oxalica** [comment]
> making the path to said formatter configurable

That's only applicable for full-file-formatting before saving. For small text-edits, like renaming or on-enter events, we need to handle it in our own code.

**Comment by IvarWithoutBones** [comment]
> I'm happy to implement this but... The main issue is that there's currently no acknowledged formatting standard for Nix.
You can see the long long debate under https://github.com/NixOS/rfcs/pull/101

Right, that makes sense. Just to clarify, are you opposed adding support for one of the existing formatters before that issue is resolved?

> IMO, nixpkgs-fmt is too relaxed and does almost nothing, nixfmt is too strict and breaks semantics, alejandra is ugly and doesn't match existing code style in nixpkgs.

I agree with all of your opinions here. `nixpkgs-fmt` being so relaxed makes it the best option to me, since it at least takes care of basic stuff like indentation, etc.
