### ISSUE TITLE
Fail silently (or silenter)

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [oxalica/nil#122]
When LSP loads it throws errors such as:
![image](https://github.com/oxalica/nil/assets/23264966/0cbda815-44ac-445d-a991-a2ce60ca824c)

Also, I had the whole screen spammed due to `import-from-derivation`, maybe this one should be enabled by default? That sounds like an easy fix for this issue

**Comment by NovaViper** [comment]
I'm having similar issues too, except in my case, my entire computer will end up locking up because it uses all of my ram to run `nix flake show` 👀 
I get this error inside of Doom Emacs
```
LSP :: Flake input "home-manager" cannot be evaluated: Nix exceeds memory limit
LSP :: Flake input "nixvim" cannot be evaluated: `nix flake show path:/nix/store/5r2d0vxwlzhg2r4p1bfgpxrn18rwwyan-source` failed with exit status: 1. Stderr:
```

Is there a way to disable this feature from running? It ends up making my computer slow down severely

**Comment by NovaViper** [comment]
That fixed it, thank you!
