### ISSUE TITLE
Better handling of the formatter

### ISSUE THREAD

**Issue by thefossguy** [oxalica/nil#128]
I'm not sure what title should be given to this issue but I'm facing a unique (so far) issue. I don't have `nixpkgs-fmt` installed "system-wide". Instead, with home-manager, I do something like this:

```
programs.neovim.extraPackages = with pkgs; [
    nixpkgs-fmt
    # many more pkgs, obviously
];
```

Mainly because these are only **needed** for a nice Neovim experience and therefore, I don't want them in my `$PATH`. As a result, format on save with [this config](https://github.com/thefossguy/dotfiles/blob/01dbb94c3b7021e74a6f487233fa6cdc31508f63/.config/nvim/lua/plugins/autocomplete.lua#L214-L230) doesn't work for me. Unsurprisingly, `!nixpkgs-fmt %` works.

Is there a workaround or do I need to have `nixpkgs-fmt` in `$PATH`?

**Comment by thefossguy** [comment]
Possible duplicate of #123?

**Comment by oxalica** [comment]
In [your config](https://github.com/thefossguy/dotfiles/blob/01dbb94c3b7021e74a6f487233fa6cdc31508f63/.config/nvim/lua/plugins/autocomplete.lua#L214-L230), you use a relative command line.
> `command = { "nixpkgs-fmt" }`

Of course it requires it to be accessible from `$PATH`. You can manage LSP settings by nix, and use absolute path, like [this](https://github.com/oxalica/nil/blob/52304da8e9748feff559ec90cb1f4873eda5cee1/dev/vim-coc.nix#L102).
