### ISSUE TITLE
My LSP client doesn't support confirmation error

### ISSUE THREAD

**Issue by heitorPB** [oxalica/nil#131]
I'm trying to setup `nil` in NeoVim but I'm getting this message whenever I open NeoVim: `Your LSP client doesn't support confirmation. You can enable autoArchive in lsp configuration.`

Here's my configuration:

```nix
autostart = true,
capabilities = caps,
cmd = { "nil" },
settings = {
    ["nil"] = {
      formatting = { command = { "nix fmt" }, },
      nix = { flake = { autoArchive = true }, },
    },
},
```

Running `nil 2023-08-09`.

What am I missing here?

**Comment by leoperegrino** [comment]
Same thing here

**Comment by leoperegrino** [comment]
Ok, I've just managed to solve it thanks to this random [git commit](https://git.pegasust.com/pegasust/dotfiles/commit/7c4b7d0db6a61f9a6e6aae186c5eaa420df1b736?style=unified&whitespace=ignore-change&show-outdated=) I've found on google. The solutions lies in changing the `lspconfig` parameters of the `nil_ls` server. Documentation can also be found [here](https://github.com/oxalica/nil/blob/main/docs/configuration.md).

```lua
require('lspconfig').nil_ls.setup {
  settings = {
    nix = {
      flake = {
        -- calls `nix flake archive` to put a flake and its output to store
        autoArchive = true,
      },
    },
  },
}

```
