### ISSUE TITLE
Completions only showing after typing a letter

### ISSUE THREAD

**Issue by amacfie** [oxalica/nil#133]
I'm seeing this in vim-lsp and lsp4ij, others have seen it in emacs: https://github.com/doomemacs/doomemacs/issues/7735.

Example file (test.nix):
```
{ config, lib, pkgs, ... }:

{
  foo = builtins.
}
```

Putting cursor after `builtins.` and triggering completion has no result, but typing a letter like `a` and then triggering completion brings up the expected list.

[log.txt](https://github.com/oxalica/nil/files/15094483/log.txt)

**Comment by oxalica** [comment]
Vim/coc.nvim, Neovim/native lsp and VSCodium all work well. I think emacs is to be blamed here. Also that you can retry with the latest `master` build.

![Screenshot_20240530_124520](https://github.com/oxalica/nil/assets/14816024/bf8dc3b7-24f2-42ef-893b-b850a92114cc)

**Comment by amacfie** [comment]
Could you compare the log I included with the log from an editor where it works? The log shows that no completions are returned.
