### ISSUE TITLE
`cargo install` fails with `2023-08-09` tag

### ISSUE THREAD

**Issue by cospectrum** [oxalica/nil#147]
Build of `2023-08-09` tag fails (started by [mason.nvim](https://github.com/williamboman/mason.nvim)). 
Although I managed to install the latest version with `nix profile install github:oxalica/nil`. 
`cargo install` with `2024-08-06` tag seems to work too.

## cmd
```sh
cargo install --root . --git https://github.com/oxalica/nil --tag 2023-08-09 --locked nil
```
OS: `mac`
cargo: `1.79.0`

## fail msg
```sh
error: failed to run custom build command for `builtin v0.0.0 (/Users/.../.cargo/git/checkouts/nil-d84aa7a39c766408/97abe7d/crates/builtin)`

Caused by:
  process didn't exit successfully: `/var/folders/cd/w9n829x50wd3h5vghjxflpk00000gn/T/cargo-installamFzUY/release/build/builtin-081cf49527d42538/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at crates/builtin/build.rs:155:10:
  failed to dump builtin docs: "Command \"nix\" \"__dump-builtins\" failed: Output { status: ExitStatus(unix_wait_status(256)), stdout: \"\", stderr: \"error: '__dump-builtins' is not a recognised command\\nTry 'nix --help' for more information.\\n\" }"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nil v0.0.0 (https://github.com/oxalica/nil?tag=2023-08-09#97abe7d3)`, intermediate artifacts can be found at `/var/folders/cd/w9n829x50wd3h5vghjxflpk00000gn/T/cargo-installamFzUY`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

## possible solution
Make sure that [mason.nvim](https://github.com/williamboman/mason.nvim) and others are using the latest tag

**Comment by oxalica** [comment]
Could you provide the version of nix (output of `nix --version`)?

**Comment by cospectrum** [comment]
nix (Nix) 2.24.2

**Comment by oxalica** [comment]
> Build of `2023-08-09` tag

> nix (Nix) 2.24.2

It should already be fixed recently in 01a62046a7e707bcef5f37c14f390fe821d39983 which is only available since tag [2024-08-06](https://github.com/oxalica/nil/releases/tag/2024-08-06). Please retry on the latest release of nil.

**Comment by cospectrum** [comment]
Yeah, I think it was fixed. Hope `mason` will update tag

**Comment by cospectrum** [comment]
https://github.com/williamboman/mason.nvim/discussions/1767

**Comment by cospectrum** [comment]
Mason updated https://github.com/mason-org/mason-registry/pull/6926
