### ISSUE TITLE
How display information about builtins function?

### ISSUE THREAD

**Issue by pleshevskiy** [oxalica/nil#15]
Looks like a new feature doesn't work yet. Or maybe I missed something.

![image](https://user-images.githubusercontent.com/7839004/191849141-dfde462a-987a-4aea-acf1-8fd964f5f87b.png)

![image](https://user-images.githubusercontent.com/7839004/191849095-b7dd6b2a-7c01-45f4-b911-c9a98f01613a.png)

**Comment by pleshevskiy** [comment]
![image](https://user-images.githubusercontent.com/7839004/191849459-39761ec5-8170-4a01-bb6d-a23bcaea8376.png)

It works without `builtins`... but it's ok with `map`, but what about `readFile`?

**Comment by pleshevskiy** [comment]
![image](https://user-images.githubusercontent.com/7839004/191849754-e1008e44-8a36-4871-9cec-80f283a0fcfb.png)

we cannot use it :)

**Comment by pleshevskiy** [comment]
Seems like nil add prefix `builtins.` to get info about function

**Comment by pleshevskiy** [comment]
I'm trying to investigate myself.
Something goes wrong in the name_resolution 🤔 
![image](https://user-images.githubusercontent.com/7839004/191859235-fad26629-7d28-49db-8d42-b52c0f00f0f5.png)

**Comment by pleshevskiy** [comment]
I tried to add `Expr::Literal` to the `nameres` and it works now with `builtins.map`, `builtins.fetchGit` and maybe with other builtin functions we can use globally. But now I get "Undefined name" trash in diagnostic on each literal

**Comment by oxalica** [comment]
> Looks like a new feature doesn't work yet. Or maybe I missed something.
> 
> ![image](https://user-images.githubusercontent.com/7839004/191849141-dfde462a-987a-4aea-acf1-8fd964f5f87b.png)

This is expected. We pull in documentations from Nix's code and `builtins` itself (attrset) doesn't have documentation. You can verify it in `nix repl`.
```
nix-repl> :doc builtins
error: value does not have documentation
```

> It works without builtins... but it's ok with map, but what about readFile?

Currently this feature only works for global names, like `map`. Attribute forms `builtins.map`, indirection `let a = builtins.map; in a` are not supported yet. They relies on type system #14, if we don't want to hard code the handling of builtin names.

> I tried to add Expr::Literal to the nameres and it works now with builtins.map, builtins.fetchGit

No. That's wrong. `builtins.map` is selecting attribute string `"map"` from global `builtins`. We simply cannot resolve the string `map` in global scope. We don't want to show docs of `map` for any `foo.map`.

**Comment by pleshevskiy** [comment]
> if we don't want to hard code the handling of builtin names.

Wouldn't we have to hardcode for `builtins.*` anyway?

> No. That's wrong. builtins.map is selecting attribute string "map" from global builtins. We simply cannot resolve the string map in global scope. We don't want to show docs of map for any foo.map.

Yes) I'm still learning how your code works so I tried the method blindly) But now I understand that it really won't work that way.
But the idea was something like "If the scope is builtins, then check the literal behind it".

**Comment by oxalica** [comment]
I added [an indicator](https://github.com/oxalica/nil/commit/02be7d96283a43f99df64c5867045423de6bbd0b#diff-2a47269e570b8e48c1ce2c9a4f55eabe41e1c3a3367c975ad3c7055fe6951756R170-R172) for builtin names recognized but with no doc to show. Hope it could reduces some confusion.

> > if we don't want to hard code the handling of builtin names.
> 
> Wouldn't we have to hardcode for `builtins.*` anyway?

In #14, "(5) Find definition information of attribute lib.optional." covers this. Thus we only need to give a type for `builtins`, with docs as metadata. Hard-coding doesn't solve `let inherit (builtins) attrNames; in map` or `with builtins; attrNames`, which are most common usages of `builtins` IMO.
