### ISSUE TITLE
Unhandled notification: textDocument/didSave

### ISSUE THREAD

**Issue by googleson78** [oxalica/nil#158]
Hi, thanks for the project!

I'm using nvim+LanguageClient-neovim, and I keep getting the following error in my logs, as well as having the server crash and restart on every file save:
```
2024-11-28T10:18:08.900381Z ERROR nil: Unexpected error: Unhandled notification: textDocument/didSave
```
Is this something caused by LanguageClient-neovim behaving poorly, or am I hitting some unimplemented feature (or something else entirely??)

**Comment by oxalica** [comment]
> textDocument/didSave

According to [LSP 3.17](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_synchronization), it's not one of mandatory-support notifications nor ignore-able notifications (`$/*`), and we [do not advertise it during negotiation](https://github.com/oxalica/nil/blob/2e24c9834e3bb5aa2a3701d3713b43a6fb106362/crates/nil/src/capabilities.rs#L59). I think it's client's fault to send it.

I'm using [coc.nvim](https://github.com/neoclide/coc.nvim) and have not ever encountered this issue.
