### ISSUE TITLE
Rename: Does not correctly take the original value for renaming

### ISSUE THREAD

**Issue by pleshevskiy** [oxalica/nil#18]
When I try to rename a variable with a dash, it shows part of the variable name.

Cursor was on `treesitter` part.
![image](https://user-images.githubusercontent.com/7839004/192099236-d216d270-0e3b-4bb1-8c8a-a2d58da1121c.png)

![image](https://user-images.githubusercontent.com/7839004/192099282-d2d82417-547a-4f05-ace0-12d916af3534.png)

![image](https://user-images.githubusercontent.com/7839004/192099293-2fe9958c-a5d7-4130-8dc5-9c2d053cd0bd.png)

but renames the entire value of the variable. This is ok.

**Comment by oxalica** [comment]
Cannot not reproduce with nvim LSP and `coc.nvim`.

Could you provide the editor version and plugins you are using, and the full content of Nix file?

**Comment by pleshevskiy** [comment]
```
➜ nvim --version                                                                                                                                                                                                                                                              nix-shell
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/jnfqzl7lzqshbqfm9mkl27024nsbcgvz-neovim-unwrapped-0.7.2/share/nvim
"
```

My config - https://git.pleshevski.ru/mynix/neovim

**Comment by pleshevskiy** [comment]
Removed lspsaga. Everything is fine without it! Then no complaints to nil! I'll open the issue upstream
