### ISSUE TITLE
bug: unhelpful warning for toplevel let

### ISSUE THREAD

**Issue by MonAaraj** [oxalica/nil#20]
When using top-level `let` (for an example, i haven't thoroughly tested this and I don't know if this bug occurs anywhere else, though it probably does), nil reports a warning when it should report an error:
> warning: `let { ... }` is deprecated. Use `let ... in ...` instead.
This should be an error, as trying to compile such code results in
```
error: syntax error, unexpected LET

       at /nix/store/wlrsnx6p5kbjzjbr0m2vsnjqcm7pzfaa-source/home.nix:12:3:

           11|
           12|   let
             |   ^
           13|     emailConf = { name, maildirName, realName, address, folder, primary ? false, flavor ? "plain" }:
```
which isn't as helpful of an error, but nil could improve upon it by saying "top-level `let` is not allowed, `let` is only allowed in expressions."

**Comment by oxalica** [comment]
Could you provide the full content of that Nix file?

**Comment by MonAaraj** [comment]
Not anymore, but it was just (with some sensitive information blimped out):
```nix
{
  config, 
  pkgs,
  inputs,
  ...
}: {
  imports = [
    ...
  ];
  
  let 
    emailConf = { name, maildirName, realName, ... }: { ... };
  in {
    accounts.email.accounts = { ... };
  };
```
it was exactly this, except I replaced thhe very long irrelevant parts with `...`.

**Comment by pleshevskiy** [comment]
@MonAaraj You have the wrong usage of `let in`. You need to raise the `let` higher.

```nix
{
  config, 
  pkgs,
  inputs,
  ...
}: 
let
  emailConf = { name, maildirName, realName, ... }: { ... };
in {
  imports = [
    ...
  ];
  
  accounts.email.accounts = { ... };
```

**Comment by MonAaraj** [comment]
I know. I wasn't asking about Nix support for what it's worth, I was just mentioning that the warning that nil reports is not very helpful, and that it should report an error instead.
