### ISSUE TITLE
VSCode "Nix IDE" doesn't pass formatter options to the server

### ISSUE THREAD

**Issue by pwm** [oxalica/nil#24]
Hi,

I bumped into your project and wanted to give it a spin as an alternative to `rnix-lsp` but ran into the following error when eg. trying to format a nix file:

```
2022-10-02T11:25:50.589363Z ERROR nil::state: Unhandled notification: Notification { method: "workspace/didChangeWatchedFiles", params: Object {"changes": Array [Object {"type": Number(2), "uri": String("file:///<redacted>/packages.nix")}]} }
```

I'm running on a Macbook M1 Max, using `home-manager` and have these versions:

```
nixpkgs: 854fdc68881791812eddd33b2fed94b954979a8e
vscode: 1.71.2, 74b1f979648cc44d385a2286793c226e611f59e7, x64
nix-ide: 0.1.23, 0i5zqfz2ic57z9b4v6mrs68dzhvgpnr5984srjapi0nzm30k127b
```

**Comment by oxalica** [comment]
That notification kind is not supported yet. But the error should not break existing functionalities, or does it?

**Comment by pwm** [comment]
@oxalica thanks for the quick reply. Code formatting is broken for me but I'm not 100% sure whether that's because of the above? If I switch back to `rnix-lsp` then formatting works. Other functionalities do work!

**Comment by oxalica** [comment]
We don't set any "default" formatter. You must set the formatter binary to make it work.
It should be set though LSP setting `formatting.command`. I'm not sure how the vscode plugin you used passing it.

https://github.com/oxalica/nil/blob/main/docs/features.md

But "Nix IDE" pass an empty option set to the server, when LSP is enabled: https://github.com/nix-community/vscode-nix-ide/blob/d3ac20ab8d8464af30c43d468784983ea893029c/src/client.ts#L32-L35
Seems "Nix IDE" doesn't currently support passing user-defined settings to the server.

**Comment by pwm** [comment]
Hi, yes, I'm using the recommended "Nix IDE" plugin and currently have it configured as:
```
  "nix.enableLanguageServer": true,
  "nix.formatterPath": "nixpkgs-fmt",
  "nix.serverPath": "niv",
```
but was not aware that it passes an empty option set upon LSP=true. Thank you for opening the relevant issue in there!

**Comment by pwm** [comment]
@farwyler thanks for the heads up!

**Comment by oxalica** [comment]
They now implemented vscode settings `nix.serverSettings`. Check their [README](https://github.com/nix-community/vscode-nix-ide#features).

**Comment by pwm** [comment]
Works beautifully now! Thanks again!
