### ISSUE TITLE
Broken Monokai in VS Code

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [oxalica/nil#26]
nil on:
![image](https://user-images.githubusercontent.com/48378098/200433120-d6fae0be-4cbe-4650-b2f1-077efbf1e48a.png)

nil off:
![image](https://user-images.githubusercontent.com/48378098/200433201-023ea767-66c1-47fe-b65f-3455eb882fab.png)

**Comment by oxalica** [comment]
I assume you are referring to the builtin theme "Monokai Theme".

I tried it in `vscodium`, and this theme seems *intentionally* make local variables and field names white.
Here's a similar code but in typescript,

![screenshot-2022-11-10-09-15-15](https://user-images.githubusercontent.com/14816024/200976480-f6805481-2444-4224-90ed-dcc98ead51f6.png)

I think there's nothing going wrong. If you don't like this coloring, you could change to another theme.
