### ISSUE TITLE
Mistake in syntax highlighting

### ISSUE THREAD

**Issue by DavHau** [oxalica/nil#28]
In the end of the following file, red curly brackets appear, but the file is valid:
https://github.com/nix-community/dream2nix/blob/e98ca58528f9b4d1fa8cc3135c02c4306ec81364/src/subsystems/python/builders/simple-python/default.nix

**Comment by oxalica** [comment]
Please provide your editor name, plugins and settings. 

`nil` doesn't provide syntax highlighting. We only provides semantic tokens (if you enable it), and the coloring is done by your editor theme.

**Comment by DavHau** [comment]
I set it up with vscode like pointed out in the readme using the nix-ide plugin with settings:
```json5
{
  // ...
  "nix.enableLanguageServer": true, // Enable LSP.
  "nix.serverPath": "nil" // The path to the LSP server executable.
}
```

This is what is shown in the editor (red usually means syntax error, but there is none):
![image](https://user-images.githubusercontent.com/42246742/201334378-04b09404-73de-435b-a5b1-43e8fcc38ebe.png)

**Comment by oxalica** [comment]
Cannot reproduce. Could you provide the output of your `nil --version`?
Please ensure both `nil` and `Nix IDE` plugin are on their latest versions. If you have other plugins or theme installed, also try to disable them.

![image](https://user-images.githubusercontent.com/14816024/201334896-df54bf1b-9753-46a2-b740-5e2fa19110f9.png)

**Comment by DavHau** [comment]
nil 2022-11-10 a13e89c

**Comment by DavHau** [comment]
Something might be wrong.
If I type something completely invalid into `nix.serverPath`, it complains about not finding the server, but still highlights the code with the same broken patterns. So I guess it just defaults to some other server and does that even when I configure it to use `nil`.

**Comment by DavHau** [comment]
OK, now it works. It was some issue with managing vscode declaratively, but having `programs.vscode.mutableExtensionsDir = true`.
The state shown in my vscode extensions GUI was not representing reality. Now, after disabling `mutableExtensionsDir`, everything works as expected.

Sorry for wasting your time on this. At least this might be useful for others having the same issue.
