### ISSUE TITLE
Warn about unused parameters in a function when the parameter set contains `,...`

### ISSUE THREAD

**Issue by Weathercold** [oxalica/nil#33]
It would be very useful to warn when a function's parameter set that contains `...` has unused parameters. For example, in the following code,
```nix
{ foo, bar, baz, ... }:

bar { inherit baz; }
```
warn about `foo` because it was never used.

**Comment by oxalica** [comment]
Technically there are semantic difference between `{ foo, ... }: 42` and `{ ... }: 42`. `foo` is required in the former but optional in the latter.

Currently diagnostics are conservative to reduce annoying false-positives. If we want to warn more, we should also come up a way to explicit mark it "intended".

**Comment by Weathercold** [comment]
Closing as this is implemented now. Thank you!
