### ISSUE TITLE
Ignore generated files

### ISSUE THREAD

**Issue by NobbZ** [oxalica/nil#34]
I do use `nil` as the goto LSP for any project that is using Nix.

As soon as I open a single nix file, the working directory is scanned and I see how warnings appear in the "problems" pane of my editor.

These warnings are usually from generated nix expressions, be it via `yarn2nix`, `cargo2nix` or other similar tools.

Is there a way to exclude those files from the linting? Even if opened manually?

**Comment by oxalica** [comment]
Should be easy to implement via a new LSP setting.

**Comment by oxalica** [comment]
Implemented in 84e39a65c969ef737b7af272d2cd3e7009f47dc5
