### ISSUE TITLE
Quoted attribute names seem to cause trouble

### ISSUE THREAD

**Issue by NobbZ** [oxalica/nil#4]
In the following snippet I get one warning and 3 errors:

```nix
inputs: let profiles = "profiles"; in {
  "${profiles}" = import ./profiles inputs;
}
```

* default.nix:2:6-14: "Undefined name"
* default.nix:2:19-25: "Undefined name"
* default.nix:2:37-43: "Undefined name"
* default.nix:1:13-21: "Unused binding"

**Comment by oxalica** [comment]
Fixed in 92c5603498e82bcd61ad5adbacb53d6ae40c3a27
