### ISSUE TITLE
Highlight `true` and `false` differently

### ISSUE THREAD

**Issue by figsoda** [oxalica/nil#52]
I'm not aware of anything that can refer to booleans in the [standard token types and modifiers](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers), but rust-analyzer seems to [use](https://github.com/rust-lang/rust-analyzer/blob/1bd1a095936f2c16493743a05f6f14285c98ec8a/crates/ide/src/syntax_highlighting/tags.rs#L160) `bool_literals`, maybe we can use that too

**Comment by oxalica** [comment]
> but rust-analyzer seems to [use](https://github.com/rust-lang/rust-analyzer/blob/1bd1a095936f2c16493743a05f6f14285c98ec8a/crates/ide/src/syntax_highlighting/tags.rs#L160) `bool_literals`,

No. It's translated into [`boolean` for LSP semantic tokens](https://github.com/rust-lang/rust-analyzer/blob/17cc78f169538538a10e11251562e0fde8ed4958/crates/rust-analyzer/src/semantic_tokens.rs#L58).

Currently we already highlighted `true`, `false` and `null` with tag `constant` and modifier `builtin`.
https://github.com/oxalica/nil/blob/0eff7fc333e3c0c064a6339834b44feae00fe64a/crates/nil/src/semantic_tokens.rs#L89-L99

I'm using coc.nvim and `CocSemBuiltinConstant` can customize it. Or do you mean to separate `true`/`false` from `null`?

**Comment by figsoda** [comment]
> Or do you mean to separate true/false from null?

yes
