### ISSUE TITLE
Type inference for flake inputs

### ISSUE THREAD

**Issue by figsoda** [oxalica/nil#54]
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }: {
    
  };
}
```

for a flake like this, it would be nice to get completions and types for `self` and `nixpkgs`
Here is a list of attributes copied from [docs](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-flake.html#flake-format): `outPath`, `rev`, `revCount`, `lastModifiedDate`, `lastModified`, `narHash`

**Comment by oxalica** [comment]
The flake inputs recognition is working in progress. I'll hopefully got it implemented in the next week, after the Lunar New Year holiday.

**Comment by oxalica** [comment]
Ref: #76
