### ISSUE TITLE
Warn about unused non-record function arguments

### ISSUE THREAD

**Issue by poscat0x04** [oxalica/nil#55]
# Proposed feature

Add a warning for simple (non-record, i.e., not of the form `{ xxx }`) function arguments that

1. Does not have underscore (`_`) preceding its name
2. Not used in the function body

For example, the following code will have this warning (on the variable `y`).

```nix
x: y: x
```

While this code

```nix
x: _: x
```

or this code

```nix
x: _y: x
```

will not.

**Comment by oxalica** [comment]
> Add a warning for simple (non-record, i.e., not of the form `{ xxx }`) function arguments that
> 
>     1. Does not have underscore (`_`) preceding its name
> 
>     2. Not used in the function body

`_` starting identifiers are now ignored from liveness check. Note that `{ a }: 42` will still not trigger a warning since it's different from `_: 42`: the former requires the argument to be in the given form, or it will throw even without evaluating it.
