### ISSUE TITLE
Failed to load flake workspace: Failed to resolve falke inputs from lock file: Missing followed input "flake-utils-2"

### ISSUE THREAD

**Issue by benwis** [oxalica/nil#59]
I installed nil successfully and am using it with neovim, and it works for some files fine. In one project, my flake.nix gives this
```
Failed to load flake workspace: Failed to resolve flake inputs from lock file: Missing followed input "flake-utils-2"
```
Is there something I can do to fix this?

**Comment by oxalica** [comment]
Seems like #56 and should be already fixed in `master`. You can run `nil --version` to show the version you are using.

**Comment by benwis** [comment]
Ah, I should try main. Here's my version, it's whatever is in nix unstable right now.
```
nil --version
nil 2023-02-03
```

------- Original Message -------
