### ISSUE TITLE
Doesn't load flake inputs in neovim

### ISSUE THREAD

**Issue by yavko** [oxalica/nil#61]
I get this error in neovim: `LSP[nil_ls] Failed to load flake workspace: Failed to resolve flake inputs from lock file: Missing followed input "nixpkgs_6" `
I have no clue what this means, so idk how to fix it, idk if its a me thing, or a nil thing, so I'm making this issue.

**Comment by oxalica** [comment]
Seems dup of #58. Does the latest git `master` fixes for you? There will be another release soon.

**Comment by yavko** [comment]
> Seems dup of #58. Does the latest git `master` fixes for you? There will be another release soon.

Let me switch to flake rq then, i also started getting this error
`LSP[nil_ls] Failed to load flake workspace: Failed to resolve flake inputs from lock file: Missing followed input "rust-overlay_2"`

**Comment by yavko** [comment]
Fixed!
