### ISSUE TITLE
Error when opening a Nix file

### ISSUE THREAD

**Issue by RaitoBezarius** [oxalica/nil#78]
With the recent nixpkgs bump of nil, I'm getting:

```
LSP[nil_ls] Failed to evaluate NixOS options: Nix eval failed with exit status: 1. Stderr:                                                                            
error: attribute 'renderOptionValue' missing                                                                                                                          
       at «string»:5:4:                                                                                                                                               
            4| nixpkgs:                                                                                                                                               
            5| let                                                                                                                                                    
             |    ^                                                                                                                                                   
            6|   lib = import (nixpkgs + "/lib");
```

while opening files which does not have any nixpkgs relation.

Does it ring a bell?

**Comment by oxalica** [comment]
The error is triggered when it tries to load `nixpkgs` flake input.  Do you have an input named `nixpkgs` but is not a recent enough `nixpkgs`?

**Comment by oxalica** [comment]
> Did you try running `nix flake archive`?

Should not be relevant. The failed Nix is at https://github.com/oxalica/nil/blob/2023-05-02/crates/nix-interop/src/nixos_options.nix which is used to dump all NixOS options for the flake input named "nixpkgs".

**Comment by RaitoBezarius** [comment]
> The error is triggered when it tries to load `nixpkgs` flake input. Do you have an input named `nixpkgs` but is not a recent enough `nixpkgs`?

I personally don't use flakes so I don't really know where does this input would come from neither what is its freshness, I opened this in the NixOS/Ofborg repository (maintainers.nix).

How could I debug this further?

**Comment by oxalica** [comment]
> in the NixOS/Ofborg repository

Oh [it uses nixos-22.11](https://github.com/NixOS/ofborg/blob/0f34038feb9b0ae9959c865608700c91d57b2590/flake.nix#L3). We should somehow check the revision of a dumped nixpkgs before the evaluation, but I have no clear idea.
