### ISSUE TITLE
Haumea integration

### ISSUE THREAD

**Issue by figsoda** [oxalica/nil#82]
https://github.com/oxalica/nil/commit/5b99f7aab5d2ed11ddd83fbd882a26196d96886a added completions for NixOS Options, it would be nice if this feature would work with NixOS modules loaded with [haumea](https://github.com/nix-community/haumea)

Some notable differences are:

- The top level lambda parameters doesn't need to have `...`
- Content of the files are relative to the file path, so for `src/nix.nix`, the contents of the file would be within `nix`: `{ nix = { /* contents */ }; }`

This can be discovered if the module is a lambda that calls `haumea.lib.load`, and the files would be relative to `src`: https://github.com/figsoda/cfg/blob/5d10ef36cefb3b36eb529df5a34f106c2cb4965d/flake.nix#L27

**Comment by oxalica** [comment]
Not a fan of supporting custom any library APIs, unless they are somehow endorsed by upstream (NixOS/nix or NixOS/rfcs). There are too many libraries.

**Comment by figsoda** [comment]
guess I'll wait for cross file analysis and more eval
