### ISSUE TITLE
[Emacs] `lsp-nix` package not found

### ISSUE THREAD

**Issue by 64J0** [oxalica/nil#95]
## Description:

I tried to replicate the install instructions for the LSP Emacs but got an error telling that the package `lsp-nix` was not available in neither of those repositories:

- org-elpa 
- melpa 
- gnu-elpa-mirror 
- nongnu-elpa 
- el-get 
- emacsmirror-mirror

Also, after installing the `nil` package (`nix-env -iA nixpkgs.nil`) and adding only the nix-mode, it started working apparently (at least I got some highlights).

My configuration for the Nix with LSP in Emacs:

```elisp
(use-package nix-mode
  :straight t
  :mode ("\\.nix\\'" . nix-mode)
  :hook (nix-mode . lsp-deferred))
```

Finally, my question is, where can I find the `lsp-nix` package?

**Comment by leungbk** [comment]
`lsp-nix` is not a separate "package"; it is some Lisp that is bundled with `lsp-mode`.

My guess is that you did something like

```elisp
(use-package lsp-nix
  :straight t
;; other stuff
)
;;

and were correctly told by `straight.el` that `lsp-nix` was not available in the package repositories.
